### ISSUE TITLE
Добавить проверку (в метод Song::isValid) на входные файлы.

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/AlcoParty#10]
Проверять воспроизводимые файлы, если файл файл не являетесь аудио файлов вернуть false.

**Comment by EndrII** [comment]
Нужно сделать какой нибуть список доступных расширений, метод isvalid должен проверять есть ли расширение в списке, если есть возвращать true

**Comment by EndrII** [comment]
сделай список в виде статического множества.
static const QSet<QString> validFormats;
изучи как работает [QSet](http://doc.qt.io/qt-5/qset.html)

**Comment by usermeme** [comment]
Готово [pr](https://github.com/QuasarApp/AlcoParty/pull/32)
