### ISSUE TITLE
new project Name

### ISSUE THREAD

**Issue by EndrII** [QuasarApp/AlcoParty#45]
Нужно поменять название программы.
Вот некоторые из вариантов :

1. MyParty
2. PartyHard
3. SyncBlaster
4. SyncParty
5. SyncMaker
6. MegaParty
7. SaundBand

**Comment by zig1hai** [comment]
PartyHard

**Comment by zig1hai** [comment]
SyncBlaster

**Comment by zig1hai** [comment]
одно из двух

**Comment by EndrII** [comment]
SyncBlaster смысла почти нет

**Comment by zig1hai** [comment]
SaundBand

**Comment by EndrII** [comment]
Посмотрел SaundBand в нете, вроде нет ничего.
Название нравиться, если предложений по лучше не будет можно будет оставить.

**Comment by p-nikolaichik** [comment]
MegaParty

**Comment by p-nikolaichik** [comment]
ProjectX

**Comment by EndrII** [comment]
MegaParty еще куда не шло, но  ProjectX совсем не в тему.  
SaundBand звучит эффектнее.

**Comment by p-nikolaichik** [comment]
PartyTime тогда

**Comment by EndrII** [comment]
PartyTime уже есть

**Comment by p-nikolaichik** [comment]
из того что есть SyncBlaster

**Comment by zig1hai** [comment]
Саунд банд подходит по смыслу функционала программы лучше всего

**Comment by EndrII** [comment]
Пока переименовал в SoundBand.
[Вот ПР](https://github.com/QuasarApp/AlcoParty/pull/46)

**Comment by EndrII** [comment]
принял название SoundBand
